config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :pictures do
    post :confirm, on: :collection
  end
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader

  validates :content, presence: true, length: { maximum: 2200 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture

  mount_uploader :profile_image, ProfileImageUploader

  has_secure_password
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorite_pictures.all
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to picture_path(params[:picture_id]), notice: "#お気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    if params[:name] == "favorite_index"
      redirect_to favorites_path, notice: "お気に入り解除しました"
    else
      redirect_to picture_path(favorite.picture_id), notice: "#お気に入り解除しました"
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :ensure_user, only: %i[ edit update destroy ]

  def index
    @pictures = Picture.all.order(updated_at: :desc)
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    render :new and return if params[:back]
    if @picture.save
      SubmitMailer.submit_mail(@picture).deliver
      redirect_to picture_url(@picture), notice: "新規投稿しました！"
    else
      render :new
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_url(@picture), notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy

    redirect_to pictures_url, notice: "投稿を削除しました！"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def ensure_user
    redirect_to pictures_path unless @picture.user == current_user
  end

  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to pictures_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update ]
  before_action :ensure_user, only: %i[ edit update ]

  def new
    if current_user
      redirect_to pictures_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to pictures_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_user
    redirect_to root_path unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>

<p>
  <%= "お気に入りなし。投稿一覧の「詳細」ページからお気に入り登録しよう！" unless @favorites.present? %>
</p>

<% @favorites.each do |favorite| %>
  <div class = "favorite-contents">
    <div class = "favorite-item1"><%= favorite.user.name %></div>
    <% if favorite.image? %>
      <div class = "favorite-item2"><img src="<%= favorite.image %>" id="picture_image"></div>
    <% else %>
      <div class = "favorite-item2">画像無</div>
    <% end %>
    <div class = "favorite-item3"><%= favorite.content %></div>
    <div class = "favorite-item4"><%= link_to '詳細', favorite, class: "btn btn-info" %></div>
    <div class = "favorite-item5"><%= link_to '解除', favorite_path(id: favorite.favorite_ids, name: "favorite_index"), method: :delete ,data: {confirm: "お気に入り解除してよろしいですか？"}, class: "btn btn-danger" %></div>
  </div>
<% end %>

<%= link_to '投稿一覧に戻る', pictures_path, class: "btn btn-secondary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>写真共有アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="#page-top">写真共有アプリ</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto">
            <% if logged_in? %>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "プロフィール", user_path(current_user.id), class: "nav-link py-3 px-0 px-lg-3 rounded" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "お気に入り一覧", favorites_path, class: "nav-link py-3 px-0 px-lg-3 rounded" %></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "ログアウト", session_path(current_user.id), method: :delete, class: "nav-link py-3 px-0 px-lg-3 rounded"%></li>
            <% else %>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "アカウント登録", new_user_path, class: "nav-link py-3 px-0 px-lg-3 rounded"%></li>
              <li class="nav-item mx-0 mx-lg-1"><%= link_to "ログイン", new_session_path, class: "nav-link py-3 px-0 px-lg-3 rounded"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead bg-primary text-white text-center">
      <div class="container d-flex align-items-center flex-column">
        <div class="login_status">
          <% if logged_in? %>
            <div class = "login_item">ようこそ<strong><%= current_user.name%></strong>さん</div>
            <% if current_user.profile_image? %>
              <div class = "login_item"><img src="<%= current_user.profile_image %>" id="profile_image"></div>
            <% end %>
          <% else %>
            <div class = "login_item">初めての方は「<strong>アカウント登録</strong>」を。すでにアカウントをお持ちの方は「<strong>ログイン</strong>」してください。</div>
          <% end %>
        </div>
      </div>
    </header>

    <section class="page-section portfolio" id="portfolio">
      <div class="container">

        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

        <%= yield %>
      </div>
    </section>

    <div class="copyright py-4 text-center text-white">
      <div class="container"><small>Copyright &copy; Yamada Yuji 2022</small></div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div>
      <%= form.label :image %>
    </div>
    <div>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    </div>
    <div>
      <%= form.file_field :image %>
    </div>
    <div>
      <%= form.hidden_field :image_cache %>
    </div>
  </div>

  <div class="field">
    <%= form.label :content %>
  </div>
  <div>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で投稿しますか？</h3>

<%= form_with(model: @picture, local: true, url: pictures_path) do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <p>画像:</p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <p>内容:<%= @picture.content %></p>

  <%= form.submit "登録する", class: "btn btn-primary" %>
  <%= form.submit "戻る", name: "back" ,class: "btn btn-warning"%>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿編集画面</h2>

<%= render 'form', picture: @picture %>

<%= link_to '詳細', @picture, class: "btn btn-info" %>
<%= link_to '一覧に戻る', pictures_path, class: "btn btn-secondary" %>

app/views/pictures/index.html.erb
<h2>投稿一覧</h2>

<% @pictures.each do |picture| %>
  <div class = "picture-contents">
    <div class = "picture-item1"><%= picture.user.name %></div>
    <% if picture.image? %>
      <div class = "picture-item2"><img src="<%= picture.image %>" id="picture_image"></div>
    <% else %>
      <div class = "picture-item2">画像無</div>
    <% end %>
    <div class = "picture-item3"><%= picture.content %></div>
    <div class = "picture-item4"><%= link_to '詳細', picture, class: "btn btn-info" %></div>
    <% if picture.user == current_user %>
      <div class = "picture-item5"><%= link_to '編集', edit_picture_path(picture), class: "btn btn-success" %></div>
      <div class = "picture-item6"><%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除しますか？' } ,class: "btn btn-danger" %></div>
    <% else %>
      <div class = "picture-item5"></div>
      <div class = "picture-item6"></div>
    <% end %>
  </div>
<% end %>

<%= link_to '新規投稿', new_picture_path, class: "btn btn-primary" %>

app/views/pictures/new.html.erb
<h2>新規投稿</h2>

<%= render 'form', picture: @picture %>

<%= link_to '一覧に戻る', pictures_path, class: "btn btn-secondary" %>

app/views/pictures/show.html.erb
<p>
  <strong>投稿者:</strong>
  <%= @picture.user.name %>
</p>

<% if @picture.image? %>
  <p><%= image_tag @picture.image.url%></p>
<% end %>

<p><%= @picture.content %></p>

<div>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= button_to "お気に入り解除", favorite_path(id: @favorite.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "お気に入り登録", favorites_path(picture_id: @picture.id), method: :post, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

<% if @picture.user == current_user %>
  <%= link_to '編集', edit_picture_path(@picture), class: "btn btn-success" %>
<% end %>
<%= link_to '一覧に戻る', pictures_path, class: "btn btn-secondary" %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "名前" %>
  </div>

  <div>
    <%= form.email_field :email, placeholder: "メールアドレス" %>
  </div>

  <div>
    <%= form.password_field :password, placeholder: "パスワード" %>
  </div>

  <div>
    <%= form.password_field :password_confirmation, placeholder: "パスワード確認" %>
  </div>

  <div>
    <%= form.label :profile_image %>
  </div>
  <div>
    <%= form.file_field :profile_image %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィール編集画面</h2>

<%= render 'form' %>

<%= link_to '戻る', @user, class: "btn btn-warning" %>
<%= link_to '一覧に戻る', pictures_path, class: "btn btn-secondary" %>

app/views/users/new.html.erb
<h2>アカウント登録</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.name %>さんのプロフィール</h2>

<% if @user == current_user %>
  <div>メールアドレス: <%= @user.email %></div>
<% end %>

<div><%= image_tag @user.profile_image.url if @user.profile_image? %></div>

<% if @user == current_user %>
  <%= link_to '編集', edit_user_path(@user), class: "btn btn-success" %>
<% end %>
<%= link_to '一覧に戻る', pictures_path, class: "btn btn-secondary" %>